### ISSUE TITLE
Error: Cannot upgrade pack with status 'done'.

### ISSUE THREAD

**Issue by SavageTheUnicorn** [misode/upgrader#27] opened 2022-06-27 00:28 UTC
An error occurred while upgrading a data pack.
Data Pack: <Crazy Featur
[CrazyFeatures_Datapack_v1.2.zip](https://github.com/misode/upgrader/files/8987815/CrazyFeatures_Datapack_v1.2.zip)
es by McMakistein>

```
b@https://misode.github.io/upgrader/assets/index.c024fc22.js:20:93
    at b (src/Pack.ts:202:9)
    at io/</< (src/components/PackCard.tsx:60:15)
    at io/< (src/components/PackCard.tsx:67:37)
    at Ot (../../node_modules/preact/hooks/dist/hooks.module.js:1:2256)
    at gn/< (../../node_modules/preact/hooks/dist/hooks.module.js:1:1319)
    at gn (../../node_modules/preact/hooks/dist/hooks.module.js:1:1255)

```

**Comment by SavageTheUnicorn** [comment] 2022-06-27 00:32
NOTE: i already changed the only tag that produced an error for 1.19. changed minecraft:carpets to minecraft:wool_carpets in the piston_destroyable.json 
The issue is that the "bendy pistons" and customizable tnt dont work properly. The pistons disappear when placed, spawning smoke particles. The tnt spawns an invisible villager inside it and otherwise cant be interacted other than exploding. Cannot break, needs worldedit or explosions.

**Comment by misode** [comment] 2022-06-27 01:44
@SavageTheUnicorn I believe this is a duplicate of #13. Can you check whether the reproduction steps mentioned in the comments there match your case?

**Closed** 2022-06-27 19:19 UTC
